version: "3.8"

services:
  rayders-on-the-storm:
    build: .
    env_file:
      - .env
    volumes:
      - ./domains:/app/domains
      - ./workflows:/app/workflows
      - ./wordlists:/app/wordlists
      - ./output:/app/output
    command: ["-w", "/app/workflows/main.yaml"]
    restart: on-failure
