version: "3.8"

services:
  rayders-on-the-storm:
    image: hunter_debug
    build: .
    container_name: hunter_debug
    env_file:
      - .env
    volumes:
      - ./input:/app/input
      - ./workflows:/app/workflows
      - ./wordlists:/app/wordlists
      - ./output:/app/output
      - ./gf:/app/gf
      - ./scripts:/app/scripts
    command: ["-w", "/app/workflows/main.yaml"]
    restart: on-failure
