vars:
  OUTPUT_PATH: "output"

parallel: false
modules:

  - name: ip_resolution
    cmds:
      - |
        mkdir -p {{OUTPUT_PATH}}/ips
        cat {{OUTPUT_PATH}}/subs/all.subs.txt | \
        parallel -j50 'host {} 2>/dev/null | grep "has address" | tail -1 | awk "{print \$4}"' | \
        grep -v '^$' | anew {{OUTPUT_PATH}}/ips/all.resolved.ips.txt

  - name: shodan_enum
    cmds:
      - |
        mkdir -p {{OUTPUT_PATH}}/ips/shodan
        cat {{OUTPUT_PATH}}/ips/all.resolved.ips.txt | \
        parallel -j20 --plus '
          shodan host {} 2>/dev/null | tee {{OUTPUT_PATH}}/ips/shodan/{}.shodan.txt
        '