vars:
  OUTPUT_PATH: output/tesla
  IPS: input/tesla/ips.txt
  NOTIFY: true
  WORDLIST: wordlists/subdomains/subdomains-top1million-5000.txt
  SUBDOMAINS: output/tesla/subs/subdomains/all.subs.txt

parallel: false
modules:

  - name: create_dirs
    cmds:
      - |
        mkdir -p {{OUTPUT_PATH}}/ips
        touch {{OUTPUT_PATH}}/ips/all.ips.txt

  - name: copy_ips
    cmds:
      - |
        mkdir -p {{OUTPUT_PATH}}/ips
        cat {{IPS}} | anew {{OUTPUT_PATH}}/ips/all.ips.txt

  - name: subdomain_resolution
    cmds:
      - bash workflows/infrastructure/src/subdomain_resolution.sh '{{SUBDOMAINS}}' '{{OUTPUT_PATH}}' '{{NOTIFY}}'

  - name: sdlookup_enum
    cmds:
      - bash workflows/infrastructure/src/portscan_sdlookup.sh '{{OUTPUT_PATH}}/ips/all.ips.txt' '{{OUTPUT_PATH}}' '{{NOTIFY}}'